name: Daily M3U Scraper

on:
  schedule:
    - cron: '0 0 * * *' # Menjalankan otomatis setiap jam 00:00 UTC
  workflow_dispatch: # Memungkinkan Anda menekan tombol "Run workflow" secara manual

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Izin agar bot bisa menyimpan file kembali ke repositori Anda

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Scraper Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python update_m3u.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Mendaftarkan ketiga file hasil generate ke dalam commit
          git add sports.m3u live_event.m3u penyedia.txt
          
          git commit -m "Auto-update playlists and provider list" || echo "No changes to commit"
          git push
